---
sidebar: sidebar 
permalink: trident-get-started/intro.html 
keywords: product overview, Trident, fsx, element, google cloud, architecture, node pod, controller pod, pods, csi, sidecar 
summary: Trident 是一個由 NetApp 維護的完全支援的開源專案。它旨在幫助您使用業界標準介面（例如 Container Storage Interface（CSI））來滿足容器化應用程式的持久性需求。 
---
= 了解 Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 是一個由 NetApp 維護的完全支援的開源專案。它旨在幫助您使用業界標準介面（例如 Container Storage Interface（CSI））來滿足容器化應用程式的持久性需求。



== 什麼是 Trident ？

Netapp Trident 支援在所有流行的 NetApp 儲存平台上使用和管理儲存資源，無論是在公有雲還是在本地，包括本地 ONTAP 叢集（AFF、FAS 和 ASA）、ONTAP Select、Cloud Volumes ONTAP、Element 軟體（NetApp HCI、SolidFire）、Azure NetApp Files 和 Amazon FSx for NetApp ONTAP。

Trident 是符合容器儲存介面（CSI）標準的動態儲存編排器，可與 link:https://kubernetes.io/["Kubernetes"^] 原生整合。Trident 以單一 Controller Pod 和叢集中每個工作節點上的 Node Pod 的形式運作。詳情請參閱 link:../trident-get-started/architecture.html["Trident 架構"]。

Trident 還提供與 Docker 生態系統的直接整合，適用於 NetApp 儲存平台。NetApp Docker Volume Plugin （nDVP）支援從儲存平台到 Docker 主機的儲存資源配置和管理。詳情請參閱 link:../trident-docker/deploy-docker.html["部署適用於 Docker 的 Trident"]。


NOTE: 如果您是第一次使用 Kubernetes，您應該先熟悉link:https://kubernetes.io/docs/home/["Kubernetes 概念與工具"^]。



== Kubernetes 與 NetApp 產品的整合

NetApp 儲存產品組合與 Kubernetes 叢集的許多面向整合，提供進階資料管理功能，從而增強 Kubernetes 部署的功能、能力、效能和可用性。

.Amazon FSx for NetApp ONTAP
[%collapsible]
====
link:https://www.netapp.com/aws/fsx-ontap/["Amazon FSx for NetApp ONTAP"^] 是一項完全託管的 AWS 服務，可讓您啟動並執行由 NetApp ONTAP 儲存作業系統支援的檔案系統。

====
.Azure NetApp Files
[%collapsible]
====
https://www.netapp.com/azure/azure-netapp-files/["Azure NetApp Files"^] 是由 NetApp 提供支援的企業級 Azure 檔案共用服務。您可以在 Azure 中原生運作要求最嚴苛的基於檔案的工作負載，並獲得您期望從 NetApp 獲得的卓越效能和豐富的資料管理功能。

====
.Cloud Volumes ONTAP
[%collapsible]
====
link:https://www.netapp.com/cloud-services/cloud-volumes-ontap/["Cloud Volumes ONTAP"^] 是一款純軟體儲存設備，可在雲端執行 ONTAP 資料管理軟體。

====
.Google Cloud NetApp Volumes
[%collapsible]
====
link:https://bluexp.netapp.com/google-cloud-netapp-volumes?utm_source=GitHub&utm_campaign=Trident["Google Cloud NetApp Volumes"^] 是 Google Cloud 中完全託管的文件儲存服務，提供高效能、企業級的文件儲存。

====
.Element 軟體
[%collapsible]
====
https://www.netapp.com/data-management/element-software/["元素"^] 透過確保效能並實現簡化和精簡的儲存佔用空間，使儲存管理員能夠整合工作負載。

====
.NetApp HCI
[%collapsible]
====
link:https://docs.netapp.com/us-en/hci/docs/concept_hci_product_overview.html["NetApp HCI"^] 透過自動化日常任務，簡化資料中心的管理和擴展，使基礎架構管理員能夠專注於更重要的功能。

Trident 可以直接針對底層 NetApp HCI 儲存平台為容器化應用程式配置和管理儲存裝置。

====
.NetApp ONTAP
[%collapsible]
====
link:https://docs.netapp.com/us-en/ontap/index.html["NetApp ONTAP"^] 是 NetApp 多協定、統一的儲存作業系統，可為任何應用程式提供進階資料管理功能。

ONTAP 系統具有全快閃、混合或全 HDD 配置，並提供多種不同的部署模型：內部部署 FAS、AFA 和 ASA 叢集、ONTAP Select 和 Cloud Volumes ONTAP。Trident 支援這些 ONTAP 部署模型。

====